version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - ./docker/postgres/data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped